param(
    [Parameter(Mandatory = $true)]
    [string]$ImageDir,
    [string]$Output = "HeroImages.h"
)

if (-not (Test-Path $ImageDir)) {
    Write-Error "Image directory not found: $ImageDir"
    exit 1
}

function To-CArray([byte[]]$bytes) {
    $lines = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $chunk = $bytes[$i..([Math]::Min($i + 15, $bytes.Length - 1))]
        $hex = ($chunk | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
        $lines.Add("    $hex,")
    }
    if ($lines.Count -gt 0) {
        $last = $lines[$lines.Count - 1]
        $lines[$lines.Count - 1] = $last.TrimEnd(',')
    }
    return $lines
}

$entries = @()
Get-ChildItem -Path $ImageDir -File | Where-Object { $_.Extension -match '^\.(png|jpg|jpeg)$' } | ForEach-Object {
    $base = $_.BaseName
    if ($base -match '^\d+$') {
        $entries += [pscustomobject]@{ Id = [int]$base; Path = $_.FullName; Name = $_.Name }
    }
}
$entries = $entries | Sort-Object Id

if ($entries.Count -eq 0) {
    Write-Error "No numeric hero images found. Name files like 15321.png or 15321.jpg"
    exit 1
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// Auto-generated by generate_hero_images.ps1")
[void]$sb.AppendLine("// Hero image filenames must match hero ID, e.g. 15321.png / 15321.jpg")
[void]$sb.AppendLine("")

foreach ($entry in $entries) {
    $id = $entry.Id
    $sym = "hero_${id}"
    $bytes = [System.IO.File]::ReadAllBytes($entry.Path)
    [void]$sb.AppendLine("// $($entry.Name)")
    [void]$sb.AppendLine("const unsigned char ${sym}[] = {")
    foreach ($line in (To-CArray $bytes)) { [void]$sb.AppendLine($line) }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("const unsigned int ${sym}_len = $($bytes.Length);")
    [void]$sb.AppendLine("")
}

[void]$sb.AppendLine("inline const unsigned char* GetHeroImageBytes(int id, int* outLen) {")
[void]$sb.AppendLine("    switch (id) {")
foreach ($entry in $entries) {
    $id = $entry.Id
    $sym = "hero_${id}"
    [void]$sb.AppendLine("        case ${id}: *outLen = ${sym}_len; return ${sym};")
}
[void]$sb.AppendLine("        default:")
[void]$sb.AppendLine("            *outLen = 0;")
[void]$sb.AppendLine("            return nullptr;")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("}")

$outputPath = if ([System.IO.Path]::IsPathRooted($Output)) { $Output } else { Join-Path (Get-Location) $Output }
[System.IO.File]::WriteAllText($outputPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated $outputPath with $($entries.Count) hero images."
